<?php
// General Translation file (i18n) for Custom Page gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: CustomPage"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_CUSTOMPAGE_NAME', "Pages");
define('_EN_CUSTOMPAGE_DESCRIPTION', "A gadget to create and manage pages.");

// Actions
define('_EN_CUSTOMPAGE_ACTION_DEFAULT', "Display the default page.");
define('_EN_CUSTOMPAGE_ACTION_INDEX', "Display an index of pages.");
define('_EN_CUSTOMPAGE_ACTION_PAGE', "Display a single page.");

// Layout elements
define('_EN_CUSTOMPAGE_LAYOUT_LIST', "Page List");
define('_EN_CUSTOMPAGE_LAYOUT_LIST_DESCRIPTION', "Lists the available pages.");
define('_EN_CUSTOMPAGE_LAYOUT_SHOWPOST', "Show Post '{0}'");
define('_EN_CUSTOMPAGE_LAYOUT_SHOWPOST_DESCRIPTION', "Displays post '{0}'");
define('_EN_CUSTOMPAGE_LAYOUT_NEWPOST0', "Add New Post");
define('_EN_CUSTOMPAGE_LAYOUT_NEWPOST0_DESCRIPTION', "Add a new post to this page. Default layout.");

// ACLs
define('_EN_CUSTOMPAGE_ACL_DEFAULT', "Adminstrate Pages");
define('_EN_CUSTOMPAGE_ACL_OWNPAGE', "Add/Edit/Delete their own Pages");
define('_EN_CUSTOMPAGE_ACL_MANAGEPAGES', "Manage Pages");
define('_EN_CUSTOMPAGE_ACL_MANAGEPUBLICPAGES', "Manage Public Pages");

// Errors
define('_EN_CUSTOMPAGE_ERROR_PAGE_NOT_ADDED', "There was a problem adding the page.");
define('_EN_CUSTOMPAGE_ERROR_PAGE_NOT_UPDATED', "There was a problem updating the page.");
define('_EN_CUSTOMPAGE_ERROR_PAGE_NOT_DELETED', "There was a problem deleting the page.");
define('_EN_CUSTOMPAGE_ERROR_PAGE_NOT_FOUND', "The page you requested could not be found.");
define('_EN_CUSTOMPAGE_ERROR_POST_NOT_ADDED', "There was a problem adding the post.");
define('_EN_CUSTOMPAGE_ERROR_POST_NOT_UPDATED', "There was a problem updating the post.");
define('_EN_CUSTOMPAGE_ERROR_POST_NOT_DELETED', "There was a problem deleting the post.");
define('_EN_CUSTOMPAGE_ERROR_POST_NOT_FOUND', "The post you requested could not be found.");
define('_EN_CUSTOMPAGE_ERROR_SPLASHPANEL_NOT_ADDED', "There was a problem adding the panel.");
define('_EN_CUSTOMPAGE_ERROR_SPLASHPANEL_NOT_UPDATED', "There was a problem updating the panel.");
define('_EN_CUSTOMPAGE_ERROR_SPLASHPANEL_NOT_DELETED', "There was a problem deleting the panel.");
define('_EN_CUSTOMPAGE_ERROR_RSS_NOT_HIDDEN', "There was a problem hiding the RSS item.");
define('_EN_CUSTOMPAGE_ERROR_RSS_NOT_SHOWN', "There was a problem showing the RSS item.");
define('_EN_CUSTOMPAGE_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_CUSTOMPAGE_ERROR_PAGES_NOT_RETRIEVED', "The page index could not be loaded.");
define('_EN_CUSTOMPAGE_ERROR_INDEX_NOT_LOADED', "The page index could not be loaded.");
define('_EN_CUSTOMPAGE_ERROR_PAGE_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of pages");
define('_EN_CUSTOMPAGE_ERROR_ASPPAGE_NOT_RETRIEVED', "The Page could not be loaded: {0}.");
define('_EN_CUSTOMPAGE_ERROR_GADGETCONTENT_NOT_RETRIEVED', "The requested Gadget content could not be loaded: {0}.");
define('_EN_CUSTOMPAGE_ERROR_INVALID_TITLE', "The title cannot be empty, please choose a unique name for this item.");
define('_EN_CUSTOMPAGE_ERROR_INVALID_FAST_URL', "There is already a menu item with that title, please choose a unique name for this item.");
define('_EN_CUSTOMPAGE_ERROR_STACK_NOT_UPDATED', "There was a problem updating the stack order of this section.");
define('_EN_CUSTOMPAGE_ERROR_INVALID_URL', "There was a problem with the Image URL Type you've selected, please make sure you select the correct Type.");
define('_EN_CUSTOMPAGE_ERROR_SAVE_QUICKADD', "There was a problem adding the item.");
define('_EN_CUSTOMPAGE_ERROR_USER_PAGES_NOT_DELETED', "There was a problem deleting the user's pages.");
define('_EN_CUSTOMPAGE_ERROR_USER_PAGES_NOT_UPDATED', "There was a problem updating the user's pages.");

// Strings
define('_EN_CUSTOMPAGE_QUICKADD_ADDPAGE', "Page");
define('_EN_CUSTOMPAGE_QUICKADD_ADDPOST', "Post");
define('_EN_CUSTOMPAGE_TITLE_PAGE_INDEX', "Page Index");
define('_EN_CUSTOMPAGE_TITLE_NOT_FOUND', "Page Not Found");
define('_EN_CUSTOMPAGE_CONTENT_NOT_FOUND', "The page you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_CUSTOMPAGE_MENU_ADMIN', "View Pages");
define('_EN_CUSTOMPAGE_MENU_PAGE', "Edit Page");
define('_EN_CUSTOMPAGE_MENU_POST', "Edit Post");
define('_EN_CUSTOMPAGE_MENU_PROPERTIES', "Statistics");
define('_EN_CUSTOMPAGE_PAGE_INFO', "Page Info");
define('_EN_CUSTOMPAGE_PAGE_CONTENT', "Page Content");
define('_EN_CUSTOMPAGE_PAGE_DISPLAY', "Display Options");
define('_EN_CUSTOMPAGE_PAGE_ADVANCED', "Advanced Options");
define('_EN_CUSTOMPAGE_LAST_UPDATE', "Last Update");
define('_EN_CUSTOMPAGE_NO_PAGES', "No pages were found.");
define('_EN_CUSTOMPAGE_PAGE_DESCRIPTION', "Description");
define('_EN_CUSTOMPAGE_PAGE_KEYWORDS', "Keywords");
define('_EN_CUSTOMPAGE_PAGE_CODE', "Code (Javascript, etc)");
define('_EN_CUSTOMPAGE_POST_CREATED', "The post has been created.");
define('_EN_CUSTOMPAGE_POST_UPDATED', "The post has been updated.");
define('_EN_CUSTOMPAGE_POST_DELETED', "The post has been deleted.");
define('_EN_CUSTOMPAGE_RSS_HIDDEN', "The item has been removed.");
define('_EN_CUSTOMPAGE_SPLASHPANEL_DELETED', "The panel has been deleted.");
define('_EN_CUSTOMPAGE_PAGE_CREATED', "The page has been created.");
define('_EN_CUSTOMPAGE_PAGE_UPDATED', "The page has been updated.");
define('_EN_CUSTOMPAGE_PAGE_DELETED', "The page has been deleted.");
define('_EN_CUSTOMPAGE_PAGE_MASSIVE_DELETED', "The group of pages have been deleted");
define('_EN_CUSTOMPAGE_PAGE_AUTOUPDATED', "The page has been auto saved");
define('_EN_CUSTOMPAGE_ADD_PAGE', "Add Page");
define('_EN_CUSTOMPAGE_UPDATE_PAGE', "Update Page");
define('_EN_CUSTOMPAGE_PAGE', "Page");
define('_EN_CUSTOMPAGE_POSTS', "Posts");
define('_EN_CUSTOMPAGE_SPLASHPANEL_CONFIRM_DELETE', "Are you sure you want to delete this panel?");
define('_EN_CUSTOMPAGE_POST_CONFIRM_DELETE', "Are you sure you want to delete this post?");
define('_EN_CUSTOMPAGE_RSS_CONFIRM_DELETE', "Are you sure you don't want to show this item to the public?");
define('_EN_CUSTOMPAGE_CONFIRM_DELETE_PAGE', "Are you sure you want to delete this page?");
define('_EN_CUSTOMPAGE_CONFIRM_MASIVE_DELETE_PAGE', "Are you sure you want to delete selected pages?");
define('_EN_CUSTOMPAGE_FASTURL', "Name in Menu");
define('_EN_CUSTOMPAGE_TITLE', "Title of Page");
define('_EN_CUSTOMPAGE_DRAFT', "(Not Shown In Menu)");
define('_EN_CUSTOMPAGE_PUBLISHED', "Shown In Menu");
define('_EN_CUSTOMPAGE_SHOWINMENU', "Status");
define('_EN_CUSTOMPAGE_PAGECOL', "Columns");
define('_EN_CUSTOMPAGE_SHOW_TITLE', "Show Title");
define('_EN_CUSTOMPAGE_DEFAULT_PAGE', "Default page");
define('_EN_CUSTOMPAGE_ACTIONS', "Actions");
define('_EN_CUSTOMPAGE_NEW_GADGET', "Add Gadget");
define('_EN_CUSTOMPAGE_NEW_CONTENT', "Add Content");
define('_EN_CUSTOMPAGE_EDIT_PAGE', "Page Info");
define('_EN_CUSTOMPAGE_DELETE_PAGE', "Delete Page");
define('_EN_CUSTOMPAGE_GADGETS', "Gadgets");
define('_EN_CUSTOMPAGE_PAGE_TYPE', "Page Type");
define('_EN_CUSTOMPAGE_PARENT', "Parent");
define('_EN_CUSTOMPAGE_ACTIVE', "Active");
define('_EN_CUSTOMPAGE_CONTENT', "Content");
define('_EN_CUSTOMPAGE_START_TIME', "Start Time");
define('_EN_CUSTOMPAGE_PUBLISH_DATE', "Publish Date");
define('_EN_CUSTOMPAGE_LAYOUT', "Layout");
define('_EN_CUSTOMPAGE_NO_GADGET_ACTIONS', "This gadget does not have layout actions");
define('_EN_CUSTOMPAGE_STATISTICS_KEY', "Statistics/Script Code");
define('_EN_CUSTOMPAGE_STATISTICS_EXTRA', "Here you can enter code for tracking website statistics, etc. Google Analytics is an example of an excellent free service for in-depth statistics. Just <a target=\"_blank\" href=\"http://analytics.google.com\">click here to sign-up for Google Analytics</a> for the domain: {0}, and paste the tracking code that Google gives you into this box.");
define('_EN_CUSTOMPAGE_KEY_SAVED', "The key has been saved.");
define('_EN_CUSTOMPAGE_STACK_SAVED', "The stack order has been updated.");
define('_EN_CUSTOMPAGE_USER_PAGES_DELETED', "The user's pages have been deleted.");
define('_EN_CUSTOMPAGE_USER_PAGES_UPDATED', "The user's pages have been updated.");
define('_EN_CUSTOMPAGE_THIS_PAGE', "This Page");
define('_EN_CUSTOMPAGE_SEVERAL_PAGE', "Several Pages");
define('_EN_CUSTOMPAGE_VARIOUS', "Various");
define('_EN_CUSTOMPAGE_PREVIEW_PAGE', "Preview");
define('_EN_CUSTOMPAGE_NEWPOST_SAMPLE_TITLE', "New Post");
define('_EN_CUSTOMPAGE_NEWPOST_SAMPLE_DESCRIPTION', "This is some sample text to get you started. You should change this.");
define('_EN_CUSTOMPAGE_CONFIRM_HIDEELEMENT', "Are you sure you want to remove this item from this page? It may still show on other pages. Use the Layout gadget to delete it from all pages.");




