<?php
// General Translation file (i18n) for Store gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Store"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_STORE_NAME', "Store");
define('_EN_STORE_DESCRIPTION', "A gadget to create and manage Store.");

// Actions
define('_EN_STORE_ACTION_INDEX', "Display an index of Store categories.");
define('_EN_STORE_ACTION_CATEGORY', "Display a single Store category.");

// Layout elements
define('_EN_STORE_LAYOUT_SEARCH', "Store Search Form");
define('_EN_STORE_LAYOUT_SEARCH_DESCRIPTION', "Displays a Search Box and options for filtering products on your site.");
define('_EN_STORE_LAYOUT_SLIDESHOW_DESCRIPTION', "Displays a photo Slideshow of all Products in this Category.");
define('_EN_STORE_LAYOUT_SHOWONE', "Show Random Product in {0}");
define('_EN_STORE_LAYOUT_SHOWONE_DESCRIPTION', "Displays photo of a random Product in this Category.");
define('_EN_STORE_LAYOUT_SHOWFIVE', "Show Five Random Products");
define('_EN_STORE_LAYOUT_SHOWFIVE_DESCRIPTION', "Displays photos of five random Products.");
define('_EN_STORE_LAYOUT_PREMIUM', "\"Premium\" Product");
define('_EN_STORE_LAYOUT_PREMIUM_DESCRIPTION', "Displays a photo of a random \"Premium\" Product.");

// ACLs
define('_EN_STORE_ACL_DEFAULT', "Administrate Store");
define('_EN_STORE_ACL_OWNPRODUCT', "Add/Edit/Delete their own products");
define('_EN_STORE_ACL_MANAGEPRODUCTS', "Manage Products");
define('_EN_STORE_ACL_MANAGEPUBLICPRODUCTS', "Manage Public Products");

// Errors
define('_EN_STORE_ERROR_PRODUCT_NOT_ADDED', "There was a problem adding the product.");
define('_EN_STORE_ERROR_PRODUCT_NOT_UPDATED', "There was a problem updating the product.");
define('_EN_STORE_ERROR_PRODUCT_NOT_DELETED', "There was a problem deleting the product.");
define('_EN_STORE_ERROR_PRODUCT_NOT_FOUND', "The product you requested could not be found.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_ADDED', "There was a problem adding the category.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_UPDATED', "There was a problem updating the category.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_DELETED', "There was a problem deleting the category.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_FOUND', "The category you requested could not be found.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_LINKED', "There was a problem linking the category.");
define('_EN_STORE_ERROR_PRODUCTPARENT_NOT_UNLINKED', "There was a problem unlinking the category.");
define('_EN_STORE_ERROR_POST_NOT_ADDED', "There was a problem adding the post.");
define('_EN_STORE_ERROR_POST_NOT_UPDATED', "There was a problem updating the post.");
define('_EN_STORE_ERROR_POST_NOT_DELETED', "There was a problem deleting the post.");
define('_EN_STORE_ERROR_POST_NOT_FOUND', "The post you requested could not be found.");
define('_EN_STORE_ERROR_PRODUCTATTRIBUTE_NOT_ADDED', "There was a problem adding the attribute.");
define('_EN_STORE_ERROR_PRODUCTATTRIBUTE_NOT_UPDATED', "There was a problem updating the attribute.");
define('_EN_STORE_ERROR_PRODUCTATTRIBUTE_NOT_DELETED', "There was a problem deleting the attribute.");
define('_EN_STORE_ERROR_PRODUCTATTRIBUTE_NOT_FOUND', "The attribute you requested could not be found.");
define('_EN_STORE_ERROR_ATTRIBUTETYPE_NOT_ADDED', "There was a problem adding the attribute type.");
define('_EN_STORE_ERROR_ATTRIBUTETYPE_NOT_UPDATED', "There was a problem updating the attribute type.");
define('_EN_STORE_ERROR_ATTRIBUTETYPE_NOT_DELETED', "There was a problem deleting the attribute type.");
define('_EN_STORE_ERROR_ATTRIBUTETYPE_NOT_FOUND', "The attribute type you requested could not be found.");
define('_EN_STORE_ERROR_SALE_NOT_ADDED', "There was a problem adding the sale.");
define('_EN_STORE_ERROR_SALE_NOT_UPDATED', "There was a problem updating the sale.");
define('_EN_STORE_ERROR_SALE_NOT_DELETED', "There was a problem deleting the sale.");
define('_EN_STORE_ERROR_SALE_NOT_FOUND', "The sale you requested could not be found.");
define('_EN_STORE_ERROR_BRAND_NOT_ADDED', "There was a problem adding the brand.");
define('_EN_STORE_ERROR_BRAND_NOT_UPDATED', "There was a problem updating the brand.");
define('_EN_STORE_ERROR_BRAND_NOT_DELETED', "There was a problem deleting the brand.");
define('_EN_STORE_ERROR_BRAND_NOT_FOUND', "The brand you requested could not be found.");
define('_EN_STORE_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_STORE_ERROR_PRODUCTPARENTS_NOT_RETRIEVED', "The category index could not be loaded.");
define('_EN_STORE_ERROR_STORE_NOT_RETRIEVED', "The product index could not be loaded.");
define('_EN_STORE_ERROR_REGIONS_NOT_RETRIEVED', "The region index could not be loaded.");
define('_EN_STORE_ERROR_INDEX_NOT_LOADED', "The product index could not be loaded.");
define('_EN_STORE_ERROR_BRANDINDEX_NOT_LOADED', "The brands index could not be loaded.");
define('_EN_STORE_ERROR_PRODUCT_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of products");
define('_EN_STORE_ERROR_ASPPAGE_NOT_RETRIEVED', "The page could not be loaded: {0}.");
define('_EN_STORE_ERROR_FIELD_NOT_NUMERIC', "The {0} field can only contain numbers.");
define('_EN_STORE_ERROR_GADGETCONTENT_NOT_RETRIEVED', "The requested Gadget content could not be loaded: {0}.");
define('_EN_STORE_ERROR_KEY_NOT_SAVED', "There was a problem saving the key.");
define('_EN_STORE_ERROR_INVALID_TITLE', "The title cannot be empty, please choose a unique name for this item.");
define('_EN_STORE_ERROR_INVALID_FAST_URL', "There is already a menu item with that title, please choose a unique name for this item.");
define('_EN_STORE_ERROR_INVALID_URL', "There was a problem with the Image URL Type you've selected, please make sure you select the correct Type.");
define('_EN_STORE_ERROR_TITLE_EMPTY', "You must provide a title.");
define('_EN_STORE_ERROR_SAVE_QUICKADD', "There was a problem adding the item.");
define('_EN_STORE_ERROR_USER_BRANDS_NOT_DELETED', "There was a problem deleting the user's brands.");
define('_EN_STORE_ERROR_USER_BRAND_NOT_DELETED', "There was a problem deleting the user's brand.");
define('_EN_STORE_ERROR_USER_SALES_NOT_DELETED', "There was a problem deleting the user's sales.");
define('_EN_STORE_ERROR_USER_SALE_NOT_DELETED', "There was a problem deleting the user's sale.");
define('_EN_STORE_ERROR_USER_ATTRIBUTETYPES_NOT_DELETED', "There was a problem deleting the user's attribute types.");
define('_EN_STORE_ERROR_USER_ATTRIBUTETYPE_NOT_DELETED', "There was a problem deleting the user's attribute type.");
define('_EN_STORE_ERROR_USER_PRODUCTS_NOT_DELETED', "There was a problem deleting the user's products.");
define('_EN_STORE_ERROR_USER_PRODUCT_NOT_DELETED', "There was a problem deleting the user's product.");
define('_EN_STORE_ERROR_USER_PROPERTYPARENTS_NOT_DELETED', "There was a problem deleting the user's product categories.");
define('_EN_STORE_ERROR_USER_PROPERTYPARENT_NOT_DELETED', "There was a problem deleting the user's product category.");
define('_EN_STORE_ERROR_USER_ATTRIBUTES_NOT_UPDATED', "There was a problem updating the user's product attributes.");
define('_EN_STORE_ERROR_USER_ATTRIBUTETYPES_NOT_UPDATED', "There was a problem updating the user's amenity types.");
define('_EN_STORE_ERROR_USER_PRODUCTPARENTS_NOT_UPDATED', "There was a problem updating the user's property categories.");
define('_EN_STORE_ERROR_USER_PRODUCTS_NOT_UPDATED', "There was a problem updating the user's products.");
define('_EN_STORE_ERROR_USER_SALES_NOT_UPDATED', "There was a problem updating the user's sales.");
define('_EN_STORE_ERROR_USER_BRANDS_NOT_UPDATED', "There was a problem updating the user's brands.");

// Strings
define('_EN_STORE_QUICKADD_ADDPRODUCTPARENT', "Category");
define('_EN_STORE_QUICKADD_ADDPRODUCT', "Product");
define('_EN_STORE_TITLE_PRODUCT_INDEX', "Store Category Index");
define('_EN_STORE_DESCRIPTION_PRODUCT_INDEX', "Displays an index of Store categories.");
define('_EN_STORE_TITLE_NOT_FOUND', "Not Found");
define('_EN_STORE_CONTENT_NOT_FOUND', "The product(s) you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_STORE_MENU_ADMIN', "Categories");
define('_EN_STORE_MENU_PRODUCTS', "Products");
define('_EN_STORE_MENU_ATTRIBUTE', "Attributes");
define('_EN_STORE_MENU_ATTRIBUTETYPES', "Attribute Types");
define('_EN_STORE_MENU_SALES', "Sales");
define('_EN_STORE_MENU_SALE', "Edit Sale");
define('_EN_STORE_MENU_BRANDS', "Brands");
define('_EN_STORE_MENU_BRAND', "Edit Brands");
define('_EN_STORE_MENU_CATEGORY', "Edit Category");
define('_EN_STORE_MENU_PRODUCT', "Edit Product");
define('_EN_STORE_MENU_POST', "Edit Post");
define('_EN_STORE_MENU_SETTINGS', "Settings");
define('_EN_STORE_MENU_IMPORTINVENTORY', "Import");
define('_EN_STORE_EDIT_PRODUCTS', "Edit Products");
define('_EN_STORE_EDIT_ATTRIBUTES', "Edit Attributes");
define('_EN_STORE_EDIT_ATTRIBUTE', "Edit Attribute");
define('_EN_STORE_EDIT_ATTRIBUTETYPE', "Edit Attribute Type");
define('_EN_STORE_EDIT_SALE', "Edit Sale");
define('_EN_STORE_EDIT_BRAND', "Edit Brand");
define('_EN_STORE_LAST_UPDATE', "Last Update");
define('_EN_STORE_STARTDATE', "Start Date");
define('_EN_STORE_ENDDATE', "End Date");
define('_EN_STORE_SALE_AMOUNT', "Sale Amount");
define('_EN_STORE_NO_CATEGORY', "No categories were found.");
define('_EN_STORE_POST_CREATED', "The post has been created.");
define('_EN_STORE_POST_UPDATED', "The post has been updated.");
define('_EN_STORE_POST_DELETED', "The post has been deleted.");
define('_EN_STORE_PRODUCT_CREATED', "The product has been created.");
define('_EN_STORE_PRODUCT_UPDATED', "The product has been updated.");
define('_EN_STORE_PRODUCT_DELETED', "The product has been deleted.");
define('_EN_STORE_PRODUCT_MASSIVE_DELETED', "The group of products have been deleted");
define('_EN_STORE_PRODUCT_AUTOUPDATED', "The product has been auto saved");
define('_EN_STORE_PRODUCTPARENT_CREATED', "The category has been created.");
define('_EN_STORE_PRODUCTPARENT_UPDATED', "The category has been updated.");
define('_EN_STORE_PRODUCTPARENT_DELETED', "The category has been deleted.");
define('_EN_STORE_PRODUCTPARENT_MASSIVE_DELETED', "The group of categories have been deleted");
define('_EN_STORE_PRODUCTPARENT_AUTOUPDATED', "The category has been auto saved");
define('_EN_STORE_ADD_PRODUCT', "Add Product");
define('_EN_STORE_ADD_PRODUCTPARENT', "Add Category");
define('_EN_STORE_ADD_ATTRIBUTE', "Add Attribute");
define('_EN_STORE_ADD_ATTRIBUTETYPES', "Add Attribute Type");
define('_EN_STORE_PRODUCTATTRIBUTE_CREATED', "The attribute has been created.");
define('_EN_STORE_PRODUCTATTRIBUTE_UPDATED', "The attribute has been updated.");
define('_EN_STORE_PRODUCTATTRIBUTE_DELETED', "The attribute has been deleted.");
define('_EN_STORE_PRODUCTATTRIBUTE_MASSIVE_DELETED', "The group of attributes have been deleted");
define('_EN_STORE_PRODUCTATTRIBUTE_AUTOUPDATED', "The attribute has been auto saved");
define('_EN_STORE_ATTRIBUTETYPE_CREATED', "The attribute type has been created.");
define('_EN_STORE_ATTRIBUTETYPE_UPDATED', "The attribute type has been updated.");
define('_EN_STORE_ATTRIBUTETYPE_DELETED', "The attribute type has been deleted.");
define('_EN_STORE_ATTRIBUTETYPE_MASSIVE_DELETED', "The group of attribute types have been deleted");
define('_EN_STORE_ATTRIBUTETYPE_AUTOUPDATED', "The attribute type has been auto saved");
define('_EN_STORE_ADD_SALES', "Add Sale");
define('_EN_STORE_SALE_CREATED', "The sale has been created.");
define('_EN_STORE_SALE_UPDATED', "The sale has been updated.");
define('_EN_STORE_SALE_DELETED', "The sale has been deleted.");
define('_EN_STORE_SALE_MASSIVE_DELETED', "The group of sales have been deleted");
define('_EN_STORE_SALE_AUTOUPDATED', "The sale has been auto saved");
define('_EN_STORE_SALE_MIN_QTY_DISCLAIMER', "When you purchase {0} or more");
define('_EN_STORE_ADD_BRANDS', "Add Brand");
define('_EN_STORE_BRAND_CREATED', "The brand has been created.");
define('_EN_STORE_BRAND_UPDATED', "The brand has been updated.");
define('_EN_STORE_BRAND_DELETED', "The brand has been deleted.");
define('_EN_STORE_BRAND_MASSIVE_DELETED', "The group of brands have been deleted");
define('_EN_STORE_BRAND_AUTOUPDATED', "The brand has been auto saved");
define('_EN_STORE_UPDATE_PRODUCT', "Update Product");
define('_EN_STORE_PRODUCTPARENT', "Category");
define('_EN_STORE_PAGE', "Product");
define('_EN_STORE_PRODUCTS', "Products");
define('_EN_STORE_POSTS', "Posts");
define('_EN_STORE_POST_CONFIRM_DELETE', "Are you sure you want to delete this post?");
define('_EN_STORE_ATTRIBUTE_CONFIRM_DELETE', "Are you sure you want to delete this attribute?");
define('_EN_STORE_CONFIRM_DELETE_PRODUCT', "Are you sure you want to delete this product?");
define('_EN_STORE_CONFIRM_MASIVE_DELETE_PRODUCT', "Are you sure you want to delete selected products?");
define('_EN_STORE_CONFIRM_RSS_HIDE', "Are you sure you want to not show this product?");
define('_EN_STORE_DRAFT', "Not Active");
define('_EN_STORE_PUBLISHED', "Active");
define('_EN_STORE_IMAGE', "Image");
define('_EN_STORE_ACTIVE', "Status");
define('_EN_STORE_TITLE', "Title");
define('_EN_STORE_DESCRIPTIONFIELD', "Description");
define('_EN_STORE_PARENT', "Parent");
define('_EN_STORE_GOOGLECHECKOUT_KEY', "Google Checkout Merchant Key");
define('_EN_STORE_GOOGLECHECKOUT_ID', "Google Checkout Merchant ID");
define('_EN_STORE_GOOGLE_EXTRA', "To accept payments, you must sign up for a merchant key and ID from Google for the domain: {0}. <a target=\"_blank\" href=\"http://checkout.google.com\">Click here to sign-up for a Google Checkout</a>");
define('_EN_STORE_KEY_SAVED', "The key has been saved.");
define('_EN_STORE_NO_LISTING_DETAILS', "No details were provided for this product.");
define('_EN_STORE_IMPORTINVENTORY_TYPE', "Select File Type: (NOTE: The file you are importing MUST contain the following columns 'Vendor Name', 'Dept Name', 'Item #', 'Item Name', 'Item Description', 'Attribute', 'Size', 'Regular Price')");
define('_EN_STORE_IMPORTINVENTORY_FILE', "Inventory List File");
define('_EN_STORE_IMPORTINVENTORY_TABDELIMITED', "Tab-Delimited");
define('_EN_STORE_IMPORTINVENTORY_CSV', "Comma-Separated Values");
define('_EN_STORE_IMPORTINVENTORY_RSS', "RSS Feed");
define('_EN_STORE_URLTYPE', "URL Type");
define('_EN_STORE_INTERNALURL', "Internal URL");
define('_EN_STORE_EXTERNALURL', "External URL");
define('_EN_STORE_URLTARGET', "URL Target");
define('_EN_STORE_RANDOMIZE', "Randomize Listings");
define('_EN_STORE_DEFAULT_DISPLAY', "Default Display of Listings");
define('_EN_STORE_LIST', "List");
define('_EN_STORE_GRID', "Grid");
define('_EN_STORE_SETUP_FEE', "Setup fee");
define('_EN_STORE_RETAIL', "Retail");
define('_EN_STORE_COST', "Cost");
define('_EN_STORE_PRICE', "Price");
define('_EN_STORE_BRAND', "Brand");
define('_EN_STORE_PREMIUM', "Premium");
define('_EN_STORE_PREMIUM_DESC', "Spotlight This Listing");
define('_EN_STORE_FEATURED', "Show in Featured");
define('_EN_STORE_SUBSCRIBE_METHOD', "Subscribe Method");
define('_EN_STORE_SUBSCRIBE_METHOD_DESC', "Tie to User Gadget");
define('_EN_STORE_PRODUCTCODE', "Product Code");
define('_EN_STORE_RECURRING', "Recurring");
define('_EN_STORE_UNIT', "Unit");
define('_EN_STORE_CUSTOMUNIT', "Custom Unit");
define('_EN_STORE_MINQTY', "Minimum Quantity To Allow Purchase");
define('_EN_STORE_WEIGHT', "Weight");
define('_EN_STORE_INVENTORY_MANAGEMENT', "Use Inventory Management?");
define('_EN_STORE_INSTOCK', "In Stock");
define('_EN_STORE_LOWSTOCK', "Low Stock");
define('_EN_STORE_OUTSTOCKBUY', "Allow Purchase When Out of Stock");
define('_EN_STORE_OUTSTOCKMSG', "Message to Display When Out of Stock");
define('_EN_STORE_INTERNAL_PRODUCTNO', "Internal Product No.");
define('_EN_STORE_TYPE', "Type");
define('_EN_STORE_USER_SALES_DELETED', "The user's sales have been deleted.");
define('_EN_STORE_USER_BRANDS_DELETED', "The user's brands have been deleted.");
define('_EN_STORE_USER_ATTRIBUTETYPES_DELETED', "The user's attribute types have been deleted.");
define('_EN_STORE_USER_PRODUCTS_DELETED', "The user's products have been deleted.");
define('_EN_STORE_USER_PRODUCTPARENTS_DELETED', "The user's product categories have been deleted.");
define('_EN_STORE_USER_PRODUCTS_UPDATED', "The user's products have been updated.");
define('_EN_STORE_NO_ITEMS_MSG', "No {0} have been added yet.");
