<?php
// General Translation file (i18n) for StaticPage gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: StaticPage"
 * "Last-Translator: PADIOU Nicolas <npadiou@gmail.com>"
 * "Language-Team: FR"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_FR_STORE_NAME', "Page statique");
define('_FR_STORE_DESCRIPTION', "Un gadget pour créer et gérer du contenu statique.");

// Actions
define('_FR_STORE_ACTION_DEFAULT', "Affiche la page par défaut.");
define('_FR_STORE_ACTION_INDEX', "Affiche un index des pages statiques.");
define('_FR_STORE_ACTION_PAGE', "Affiche une simple page.");

// Layout elements
define('_FR_STORE_LAYOUT_LIST', "Liste des pages");
define('_FR_STORE_LAYOUT_LIST_DESCRIPTION', "Liste les pages statiques valables.");

// ACLs
define('_FR_STORE_ACL_DEFAULT', "Administration des pages statiques");
define('_FR_STORE_ACL_ADDPAGE', "Ajouter des pages");
define('_FR_STORE_ACL_EDITPAGE', "Editer des pages");
define('_FR_STORE_ACL_DELETEPAGE', "Supprimer des pages");

// Errors
define('_FR_STORE_ERROR_PAGE_NOT_ADDED', "Il y a eu un problème lors de l'ajout de la page.");
define('_FR_STORE_ERROR_PAGE_NOT_UPDATED', "Il y a eu un problème lors de la modification de la page.");
define('_FR_STORE_ERROR_PAGE_NOT_DELETED', "Il y a eu un problème lors de la suppression de la page.");
define('_FR_STORE_ERROR_PAGE_NOT_FOUND', "La page que vous recherchez n'a pas été trouvée.");
define('_FR_STORE_ERROR_UNKNOWN_COLUMN', "Une colonne inconnue de tri a été fournie.");
///FIXME they should not have the same translation.
define('_FR_STORE_ERROR_PAGES_NOT_RETRIEVED', "La page d'index ne peut pas être chargée.");
define('_FR_STORE_ERROR_INDEX_NOT_LOADED', "La page d'index ne peut pas être chargée.");

// Strings
define('_FR_STORE_TITLE_PAGE_INDEX', "Page index");
define('_FR_STORE_TITLE_NOT_FOUND', "Page non trouvée");
define('_FR_STORE_CONTENT_NOT_FOUND', "La page que vous recherchez n'a pas pu être trouvée, svp contactez l'administrateur du site si vous êtes sûr qu'elle existe.");
define('_FR_STORE_TITLE_INDEX', "Page index"); // ? Where is this used.
define('_FR_STORE_MENU_PAGES', "Administration des pages");
define('_FR_STORE_MENU_ADDPAGE', "Ajouter une page");
define('_FR_STORE_LAST_UPDATE', "Dernière modification");
define('_FR_STORE_NO_PAGES', "Aucune page n'a été trouvée.");
define('_FR_STORE_PAGE_CREATED', "La page a été créée.");
define('_FR_STORE_PAGE_UPDATED', "La page a été modifiée.");
define('_FR_STORE_PAGE_DELETED', "La page a été supprimée.");
define('_FR_STORE_ADD_PAGE', "Ajouter une page");
define('_FR_STORE_UPDATE_PAGE', "Modifier une page");
define('_FR_STORE_PAGE', "Page");
define('_FR_STORE_CONFIRM_DELETE_PAGE', "Êtes-vous sûr de vouloir supprimer cette page?");
define('_FR_STORE_FASTURL', "URL rapide");
define('_FR_STORE_DRAFT', "Brouillon");
define('_FR_STORE_PUBLISHED', "Publié");
define('_FR_STORE_STATUS', "Statut");
define('_FR_STORE_SHOW_TITLE', "Afficher le titre");
