<?php
// General Translation file (i18n) for StaticPage gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
// 

/**
 * Meta Data
 *
 * "Project-Id-Version: StaticPage"
 * "Last-Translator: Tadashi Jokagi <elf2000@users.sourceforge.net>"
 * "Language-Team: JA"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */
//  EN-Revision: 3650
define('_JA_STORE_NAME', "静的ページ");
define('_JA_STORE_DESCRIPTION', "静的ページの作成と管理をするガジェットです。");

// Actions
define('_JA_STORE_ACTION_DEFAULT', "デフォルトページを表示します。");
define('_JA_STORE_ACTION_INDEX', "静的ページの索引を表示します。");
define('_JA_STORE_ACTION_PAGE', "一枚のページを表示します。");

// Layout elements
define('_JA_STORE_LAYOUT_LIST', "ページ一覧");
define('_JA_STORE_LAYOUT_LIST_DESCRIPTION', "利用可能な静的ページの一覧です。");

// ACLs
define('_JA_STORE_ACL_DEFAULT', "静的ページ管理");
define('_JA_STORE_ACL_ADDPAGE', "ページを追加する");
define('_JA_STORE_ACL_EDITPAGE', "ページを編集する");
define('_JA_STORE_ACL_DELETEPAGE', "ページを削除する");

// Errors
define('_JA_STORE_ERROR_PAGE_NOT_ADDED', "ページの追加中に問題です。");
define('_JA_STORE_ERROR_PAGE_NOT_UPDATED', "ページの更新中に問題です。");
define('_JA_STORE_ERROR_PAGE_NOT_DELETED', "ページの削除中に問題です。");
define('_JA_STORE_ERROR_PAGE_NOT_FOUND', "要求したページは見つけられません。");
define('_JA_STORE_ERROR_UNKNOWN_COLUMN', "未知のソートのカラムが提供されました。");
///FIXME they should not have the same translation.
define('_JA_STORE_ERROR_PAGES_NOT_RETRIEVED', "ページ一覧を読み込むことができません。");
define('_JA_STORE_ERROR_INDEX_NOT_LOADED', "ページ一覧を読み込むことができません。");
define('_JA_STORE_ERROR_PAGE_NOT_MASSIVE_DELETED', "ページのグループを削除中にエラーです。");

// Strings
define('_JA_STORE_TITLE_PAGE_INDEX', "ページの索引");
define('_JA_STORE_TITLE_NOT_FOUND', "ページが見つかりません");
define('_JA_STORE_CONTENT_NOT_FOUND', "要求したページは見つけられません。それが存在するべきであると思う場合は、サイト管理者と連絡をとってください。");
define('_JA_STORE_TITLE_INDEX', "索引ページ"); // ? Where is this used.
define('_JA_STORE_MENU_PAGES', "ページ管理");
define('_JA_STORE_MENU_ADDPAGE', "ページを追加する");
define('_JA_STORE_LAST_UPDATE', "最後の更新");
define('_JA_STORE_NO_PAGES', "ページが見つかりませんでした。");
define('_JA_STORE_PAGE_CREATED', "ページを作成しました。");
define('_JA_STORE_PAGE_UPDATED', "ページを更新しました。");
define('_JA_STORE_PAGE_DELETED', "ページを削除しました。");
define('_JA_STORE_PAGE_MASSIVE_DELETED', "ページのグループを削除しました");
define('_JA_STORE_PAGE_AUTOUPDATED', "(草稿として)ページを自動保存しました");
define('_JA_STORE_ADD_PAGE', "ページを追加する");
define('_JA_STORE_UPDATE_PAGE', "ページを更新する");
define('_JA_STORE_PAGE', "ページ");
define('_JA_STORE_CONFIRM_DELETE_PAGE', "このページを本当に削除しますか?");
define('_JA_STORE_CONFIRM_MASIVE_DELETE_PAGE', "本当にこれらすべてのページを削除しますか?");
define('_JA_STORE_FASTURL', "ファースト URL");
define('_JA_STORE_DRAFT', "草稿");
define('_JA_STORE_PUBLISHED', "公開");
define('_JA_STORE_STATUS', "状態");
define('_JA_STORE_SHOW_TITLE', "題名表示");
define('_JA_STORE_DELETE_ALL_PAGES', "すべてのページを削除する");
