<?php
// General Translation file (i18n) for Flash Gallery gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: FlashGallery"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_FLASHGALLERY_NAME', "Gallery");
define('_EN_FLASHGALLERY_DESCRIPTION', "A gadget to create and manage galleries.");

// Actions

// Layout elements
define('_EN_FLASHGALLERY_LAYOUT_SHOWONE', "Show One");
define('_EN_FLASHGALLERY_LAYOUT_SHOWONE_DESCRIPTION', "Rotates one image at a time from a gallery.");
define('_EN_FLASHGALLERY_LAYOUT_GALLERY', "Gallery");
define('_EN_FLASHGALLERY_LAYOUT_GALLERY_DESCRIPTION', "Displays a grid of images.");
define('_EN_FLASHGALLERY_LAYOUT_SLIDESHOW', "Slideshow");
define('_EN_FLASHGALLERY_LAYOUT_SLIDESHOW_DESCRIPTION', "Displays photos as a slideshow.");

// ACLs
define('_EN_FLASHGALLERY_ACL_DEFAULT', "Adminstrate Galleries");
define('_EN_FLASHGALLERY_ACL_OWNFLASHGALLERY', "Add/Edit/Delete their own Galleries");
define('_EN_FLASHGALLERY_ACL_MANAGEFLASHGALLERIES', "Manage Galleries");
define('_EN_FLASHGALLERY_ACL_MANAGEPUBLICFLASHGALLERIES', "Manage Public Galleries");

// Errors
define('_EN_FLASHGALLERY_ERROR_GALLERY_NOT_ADDED', "There was a problem adding the gallery.");
define('_EN_FLASHGALLERY_ERROR_GALLERY_NOT_UPDATED', "There was a problem updating the gallery.");
define('_EN_FLASHGALLERY_ERROR_GALLERY_NOT_DELETED', "There was a problem deleting the gallery.");
define('_EN_FLASHGALLERY_ERROR_GALLERY_NOT_FOUND', "The gallery you requested could not be found.");
define('_EN_FLASHGALLERY_ERROR_POST_NOT_ADDED', "There was a problem adding the post.");
define('_EN_FLASHGALLERY_ERROR_POST_NOT_UPDATED', "There was a problem updating the post.");
define('_EN_FLASHGALLERY_ERROR_POST_NOT_DELETED', "There was a problem deleting the post.");
define('_EN_FLASHGALLERY_ERROR_POST_NOT_FOUND', "The post you requested could not be found.");
define('_EN_FLASHGALLERY_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_FLASHGALLERY_ERROR_GALLERIES_NOT_RETRIEVED', "The galleries could not be loaded.");
define('_EN_FLASHGALLERY_ERROR_INDEX_NOT_LOADED', "The gallery index could not be loaded.");
define('_EN_FLASHGALLERY_ERROR_GALLERY_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of galleries.");
define('_EN_FLASHGALLERY_ERROR_ASPPAGE_NOT_RETRIEVED', "The Gallery could not be loaded: {0}.");
define('_EN_FLASHGALLERY_ERROR_TITLE_EMPTY', "You must provide a title.");
define('_EN_FLASHGALLERY_ERROR_SAVE_QUICKADD', "There was a problem adding the item.");
define('_EN_FLASHGALLERY_ERROR_INVALID_URL', "The URL you've entered is malformed. Please check it.");
define('_EN_FLASHGALLERY_ERROR_INVALID_IMAGE', "Only local image URLs are allowed in the Gallery. Try using the \"Upload\" button when inserting an image.");
define('_EN_FLASHGALLERY_ERROR_USER_GALLERIES_NOT_DELETED', "There was a problem deleting the user's galleries.");
define('_EN_FLASHGALLERY_ERROR_USER_GALLERY_NOT_DELETED', "There was a problem deleting the user's gallery.");
define('_EN_FLASHGALLERY_ERROR_USER_GALLERIES_NOT_UPDATED', "There was a problem updating the user's galleries.");

// Strings
define('_EN_FLASHGALLERY_QUICKADD_ADDFLASHGALLERY', "Gallery");
define('_EN_FLASHGALLERY_QUICKADD_ADDPOST', "Post");
define('_EN_FLASHGALLERY_TITLE_GALLERY_INDEX', "Gallery Index");
define('_EN_FLASHGALLERY_TITLE_NOT_FOUND', "Gallery Not Found");
define('_EN_FLASHGALLERY_CONTENT_NOT_FOUND', "The gallery you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_FLASHGALLERY_MENU_ADMIN', "View Galleries");
define('_EN_FLASHGALLERY_MENU_GALLERY', "Edit Gallery");
define('_EN_FLASHGALLERY_MENU_POST', "Edit Post");
define('_EN_FLASHGALLERY_GALLERY_CONTENT', "Gallery Options");
define('_EN_FLASHGALLERY_GALLERY_DISPLAY', "Display Options");
define('_EN_FLASHGALLERY_GALLERY_ADVANCED', "Advanced Options");
define('_EN_FLASHGALLERY_LAST_UPDATE', "Last Update");
define('_EN_FLASHGALLERY_NO_GALLERIES', "No galleries were found.");
define('_EN_FLASHGALLERY_GALLERY_DESCRIPTION', "Description");
define('_EN_FLASHGALLERY_GALLERY_KEYWORDS', "Keywords");
define('_EN_FLASHGALLERY_POST_CREATED', "The post has been created.");
define('_EN_FLASHGALLERY_POST_UPDATED', "The post has been updated.");
define('_EN_FLASHGALLERY_POST_DELETED', "The post has been deleted.");
define('_EN_FLASHGALLERY_GALLERY_CREATED', "The gallery has been created.");
define('_EN_FLASHGALLERY_GALLERY_UPDATED', "The gallery has been updated.");
define('_EN_FLASHGALLERY_GALLERY_DELETED', "The gallery has been deleted.");
define('_EN_FLASHGALLERY_GALLERY_MASSIVE_DELETED', "The group of gallery have been deleted");
define('_EN_FLASHGALLERY_GALLERY_AUTOUPDATED', "The gallery has been auto saved");
define('_EN_FLASHGALLERY_ADD_GALLERY', "Add Gallery");
define('_EN_FLASHGALLERY_UPDATE_GALLERY', "Update Gallery");
define('_EN_FLASHGALLERY_GALLERY', "Gallery");
define('_EN_FLASHGALLERY_POSTS', "Posts");
define('_EN_FLASHGALLERY_POST_CONFIRM_DELETE', "Are you sure you want to delete this post?");
define('_EN_FLASHGALLERY_CONFIRM_DELETE_GALLERY', "Are you sure you want to delete this gallery?");
define('_EN_FLASHGALLERY_CONFIRM_MASIVE_DELETE_GALLERY', "Are you sure you want to delete selected galleries?");
define('_EN_FLASHGALLERY_TITLE', "Gallery Title");
define('_EN_FLASHGALLERY_PUBLISHED', "Published");
define('_EN_FLASHGALLERY_ACTIVE', "Status");
define('_EN_FLASHGALLERY_TYPE', "Type");
define('_EN_FLASHGALLERY_NOTPUBLISHED', "Inactive");
define('_EN_FLASHGALLERY_ALLOWFULLSCREEN', "Allow Fullscreen");
define('_EN_FLASHGALLERY_TEXTMOVE', "Text Movement");
define('_EN_FLASHGALLERY_NONE', "None");
define('_EN_FLASHGALLERY_UP', "Up");
define('_EN_FLASHGALLERY_DOWN', "Down");
define('_EN_FLASHGALLERY_LEFT', "Left");
define('_EN_FLASHGALLERY_RIGHT', "Right");
define('_EN_FLASHGALLERY_IMAGEMOVE', "Image Movement");
define('_EN_FLASHGALLERY_IMAGEOFFSETX', "Image Offset X");
define('_EN_FLASHGALLERY_IMAGEOFFSETY', "Image Offset Y");
define('_EN_FLASHGALLERY_LOADIMMEDIATELY', "Load Immediately");
define('_EN_FLASHGALLERY_USER_GALLERIES_DELETED', "The user's galleries have been deleted.");
define('_EN_FLASHGALLERY_USER_GALLERIES_UPDATED', "The user's galleries have been updated.");
