<?php
// General Translation file (i18n) for Forms gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Forms"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_FORMS_NAME', "Forms");
define('_EN_FORMS_DESCRIPTION', "A gadget to create and manage Forms.");

// Actions
define('_EN_FORMS_ACTION_INDEX', "Display an index of forms.");
define('_EN_FORMS_ACTION_FORM', "Display a single form.");

// Layout elements
define('_EN_FORMS_LAYOUT_DISPLAY', "Form");
define('_EN_FORMS_LAYOUT_DISPLAY_DESCRIPTION', "Displays a Form.");

// ACLs
define('_EN_FORMS_ACL_DEFAULT', "Adminstrate Forms");
define('_EN_FORMS_ACL_OWNFORM', "Add/Edit/Delete their own Forms");
define('_EN_FORMS_ACL_MANAGEFORMS', "Manage Forms");
define('_EN_FORMS_ACL_MANAGEPUBLICFORMS', "Manage Public Forms");

// Errors
define('_EN_FORMS_ERROR_FORM_NOT_ADDED', "There was a problem adding the form.");
define('_EN_FORMS_ERROR_FORM_NOT_UPDATED', "There was a problem updating the form.");
define('_EN_FORMS_ERROR_FORM_NOT_DELETED', "There was a problem deleting the form.");
define('_EN_FORMS_ERROR_FORM_NOT_FOUND', "The form you requested could not be found.");
define('_EN_FORMS_ERROR_POST_NOT_ADDED', "There was a problem adding the question.");
define('_EN_FORMS_ERROR_POST_NOT_UPDATED', "There was a problem updating the question.");
define('_EN_FORMS_ERROR_POST_NOT_DELETED', "There was a problem deleting the question.");
define('_EN_FORMS_ERROR_POST_NOT_FOUND', "The question you requested could not be found.");
define('_EN_FORMS_ERROR_ANSWER_NOT_ADDED', "There was a problem adding the answer.");
define('_EN_FORMS_ERROR_ANSWER_NOT_UPDATED', "There was a problem updating the answer.");
define('_EN_FORMS_ERROR_ANSWER_NOT_DELETED', "There was a problem deleting the answer.");
define('_EN_FORMS_ERROR_ANSWER_NOT_FOUND', "The answer you requested could not be found.");
define('_EN_FORMS_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_FORMS_ERROR_FORMS_NOT_RETRIEVED', "The form index could not be loaded.");
define('_EN_FORMS_ERROR_INDEX_NOT_LOADED', "The form index could not be loaded.");
define('_EN_FORMS_ERROR_FORM_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of forms");
define('_EN_FORMS_ERROR_ASPPAGE_NOT_RETRIEVED', "The page could not be loaded: {0}.");
define('_EN_FORMS_ERROR_GADGETCONTENT_NOT_RETRIEVED', "The requested Gadget content could not be loaded: {0}.");
define('_EN_FORMS_ERROR_KEY_NOT_SAVED', "There was a problem saving the key.");
define('_EN_FORMS_NOT_ADDED_TO_MENU', "There was a problem adding the default form to the menu.");
define('_EN_FORMS_ERROR_TITLE_EMPTY', "You must provide a title.");
define('_EN_FORMS_ERROR_SAVE_QUICKADD', "There was a problem adding the item.");

// Strings
define('_EN_FORMS_QUICKADD_ADDFORM', "Form");
define('_EN_FORMS_QUICKADD_ADDPOST', "Post");
define('_EN_FORMS_TITLE_PAGE_INDEX', "Form Index");
define('_EN_FORMS_TITLE_NOT_FOUND', "Form Not Found");
define('_EN_FORMS_CONTENT_NOT_FOUND', "The form you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_FORMS_MENU_ADMIN', "View Forms");
define('_EN_FORMS_MENU_FORM', "Edit Form");
define('_EN_FORMS_MENU_POST', "Edit Question");
define('_EN_FORMS_MENU_PROPERTIES', "Settings");
define('_EN_FORMS_LAST_UPDATE', "Last Update");
define('_EN_FORMS_NO_FORM', "No forms were found.");
define('_EN_FORMS_POST_CREATED', "The question has been created.");
define('_EN_FORMS_POST_UPDATED', "The question has been updated.");
define('_EN_FORMS_POST_DELETED', "The question has been deleted.");
define('_EN_FORMS_FORM_CREATED', "The form has been created.");
define('_EN_FORMS_FORM_UPDATED', "The form has been updated.");
define('_EN_FORMS_FORM_DELETED', "The form has been deleted.");
define('_EN_FORMS_FORM_MASSIVE_DELETED', "The group of forms have been deleted");
define('_EN_FORMS_FORM_AUTOUPDATED', "The form has been auto saved");
define('_EN_FORMS_ANSWER_CREATED', "The answer has been created.");
define('_EN_FORMS_ANSWER_UPDATED', "The answer has been updated.");
define('_EN_FORMS_ANSWER_DELETED', "The answer has been deleted.");
define('_EN_FORMS_ADD_FORM', "Add Form");
define('_EN_FORMS_UPDATE_FORM', "Update Form");
define('_EN_FORMS_PAGE', "Form");
define('_EN_FORMS_POSTS', "Question");
define('_EN_FORMS_POST_CONFIRM_DELETE', "Are you sure you want to delete this question?");
define('_EN_FORMS_CONFIRM_DELETE_FORM', "Are you sure you want to delete this form?");
define('_EN_FORMS_ANSWER_CONFIRM_DELETE', "Are you sure you want to delete this answer?");
define('_EN_FORMS_CONFIRM_MASIVE_DELETE_FORM', "Are you sure you want to delete selected forms?");
define('_EN_FORMS_DRAFT', "Not in Menu");
define('_EN_FORMS_PUBLISHED', "Shown in Menu");
define('_EN_FORMS_ACTIVE', "Status");
define('_EN_FORMS_TITLE', "Title");
define('_EN_FORMS_RECIPIENT_KEY', "Default Recipient");
define('_EN_FORMS_RECIPIENT_EXTRA', "Here you can specify the default e-mail address to which all forms will be submitted. If this is left blank, all forms will be submitted to the site administrator's address: {0}");
define('_EN_FORMS_ADDRESS_KEY', "Address");
define('_EN_FORMS_OFFICE_KEY', "Office Phone");
define('_EN_FORMS_TOLLFREE_KEY', "Toll-Free Phone");
define('_EN_FORMS_CELL_KEY', "Cell/Direct Phone");
define('_EN_FORMS_FAX_KEY', "Fax");
define('_EN_FORMS_KEY_SAVED', "The key(s) have been saved.");
define('_EN_FORMS_ADDED_TO_MENU', "Default form added to the menu.");
define('_EN_FORMS_PARENT', "Parent");
define('_EN_FORMS_DESC', "Description");
define('_EN_FORMS_CUSTOM_ACTION', "Custom Action");
define('_EN_FORMS_SUBMIT_CONTENT', "Submit Content");

