<?php
// General Translation file (i18n) for Ecommerce gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Ecommerce"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_ECOMMERCE_NAME', "Ecommerce");
define('_EN_ECOMMERCE_DESCRIPTION', "A gadget for processing payments, orders and subscriptions.");

// Actions

// Layout elements
define('_EN_ECOMMERCE_LAYOUT_CARTBUTTON_TITLE', "Large Add to Cart Button");
define('_EN_ECOMMERCE_LAYOUT_CARTBUTTON_DESCRIPTION', "Displays large-sized Add to Cart button, depending on your Payment Gateway");
define('_EN_ECOMMERCE_LAYOUT_SMALLCARTBUTTON_TITLE', "Small Add to Cart Button");
define('_EN_ECOMMERCE_LAYOUT_SMALLCARTBUTTON_DESCRIPTION', "Displays small-sized Add to Cart button, depending on your Payment Gateway");
define('_EN_ECOMMERCE_LAYOUT_CARTLINK_TITLE', "Add to Cart Link");
define('_EN_ECOMMERCE_LAYOUT_CARTLINK_DESCRIPTION', "Displays text link 'Add to Cart', depending on your Payment Gateway");

// ACLs
define('_EN_ECOMMERCE_ACL_DEFAULT', "Adminstrate Ecommerce");
define('_EN_ECOMMERCE_ACL_OWNECOMMERCE', "Add/Edit/Delete their own Orders");
define('_EN_ECOMMERCE_ACL_MANAGEECOMMERCE', "Manage Orders");
define('_EN_ECOMMERCE_ACL_MANAGEPUBLICECOMMERCE', "Manage Public Orders");

// Errors
define('_EN_ECOMMERCE_ERROR_RESPONSE_NOT_HANDLED', "There was a problem handling a response from the payment gateway.");
define('_EN_ECOMMERCE_ERROR_ORDER_NOT_ADDED', "There was a problem adding the order.");
define('_EN_ECOMMERCE_ERROR_ORDER_NOT_UPDATED', "There was a problem updating the order.");
define('_EN_ECOMMERCE_ERROR_ORDER_NOT_DELETED', "There was a problem deleting the order.");
define('_EN_ECOMMERCE_ERROR_ORDER_NOT_FOUND', "The order you requested could not be found.");
define('_EN_ECOMMERCE_ERROR_SHIPPING_NOT_ADDED', "There was a problem adding the shipping.");
define('_EN_ECOMMERCE_ERROR_SHIPPING_NOT_UPDATED', "There was a problem updating the shipping.");
define('_EN_ECOMMERCE_ERROR_SHIPPING_NOT_DELETED', "There was a problem deleting the shipping.");
define('_EN_ECOMMERCE_ERROR_SHIPPING_NOT_FOUND', "The shipping you requested could not be found.");
define('_EN_ECOMMERCE_ERROR_CART_NOT_ADDED', "There was a problem adding the cart.");
define('_EN_ECOMMERCE_ERROR_CART_NOT_UPDATED', "There was a problem updating the cart.");
define('_EN_ECOMMERCE_ERROR_CART_NOT_DELETED', "There was a problem deleting the cart.");
define('_EN_ECOMMERCE_ERROR_CART_NOT_FOUND', "The cart you requested could not be found.");
define('_EN_ECOMMERCE_ERROR_CARTITEM_NOT_ADDED', "There was a problem adding the item to the cart.");
define('_EN_ECOMMERCE_ERROR_CARTITEM_NOT_DELETED', "There was a problem deleting the item from the cart.");
define('_EN_ECOMMERCE_ERROR_CARTITEM_NOT_FOUND', "The item you requested could not be found in the cart.");
define('_EN_ECOMMERCE_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_ECOMMERCE_ERROR_ORDERS_NOT_RETRIEVED', "The orders could not be loaded.");
define('_EN_ECOMMERCE_ERROR_SHIPPINGS_NOT_RETRIEVED', "The shipping methods could not be loaded.");
define('_EN_ECOMMERCE_ERROR_CARTS_NOT_RETRIEVED', "The carts could not be loaded.");
define('_EN_ECOMMERCE_ERROR_INDEX_NOT_LOADED', "The order index could not be loaded.");
define('_EN_ECOMMERCE_ERROR_ORDER_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of orders.");
define('_EN_ECOMMERCE_ERROR_SHIPPING_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of shipping methods.");
define('_EN_ECOMMERCE_ERROR_ASPPAGE_NOT_RETRIEVED', "The Order could not be loaded: {0}.");
define('_EN_ECOMMERCE_ERROR_CARTBUTTON_NOT_SHOWN', "There was a problem displaying 'Add to Cart'.");
define('_EN_ECOMMERCE_ERROR_SUBMITTING_ORDER', "There was an error submitting your order. We have been notified and are working on the issue.");
define('_EN_ECOMMERCE_ERROR_SUBMITTING_ORDER_MAIL_SUBJECT', "E-commerce Order Error on {0}.");
define('_EN_ECOMMERCE_ERROR_NO_MERCHANT_ACCOUNTS', "No merchant accounts have been setup to accept this order.");
define('_EN_ECOMMERCE_SETTINGS_CANT_UPDATE', "There was a problem updating Settings.");
define('_EN_ECOMMERCE_ERROR_USER_TAXES_NOT_DELETED', "There was a problem deleting the user's tax rules.");
define('_EN_ECOMMERCE_ERROR_USER_TAX_NOT_DELETED', "There was a problem deleting the user's tax rule.");
define('_EN_ECOMMERCE_ERROR_USER_SHIPPINGS_NOT_DELETED', "There was a problem deleting the user's shipping rules.");
define('_EN_ECOMMERCE_ERROR_USER_SHIPPING_NOT_DELETED', "There was a problem deleting the user's shipping rule.");
define('_EN_ECOMMERCE_ERROR_USER_ORDERS_NOT_DELETED', "There was a problem deleting the user's properties.");
define('_EN_ECOMMERCE_ERROR_USER_ORDER_NOT_DELETED', "There was a problem deleting the user's property.");
define('_EN_ECOMMERCE_ERROR_USER_TAXES_NOT_UPDATED', "There was a problem updating the user's tax rules.");
define('_EN_ECOMMERCE_ERROR_USER_SHIPPINGS_NOT_UPDATED', "There was a problem updating the user's shipping rules.");
define('_EN_ECOMMERCE_ERROR_USER_ORDERS_NOT_UPDATED', "There was a problem updating the user's orders.");

// Strings
define('_EN_ECOMMERCE_TITLE_ORDER_INDEX', "Order Index");
define('_EN_ECOMMERCE_TITLE_NOT_FOUND', "Order Not Found");
define('_EN_ECOMMERCE_CONTENT_NOT_FOUND', "The order you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_ECOMMERCE_MENU_ADMIN', "View Orders");
define('_EN_ECOMMERCE_MENU_ORDER', "Edit Order");
define('_EN_ECOMMERCE_MENU_SHIPPING', "Shipping");
define('_EN_ECOMMERCE_MENU_TAXES', "Taxes");
define('_EN_ECOMMERCE_MENU_SETTINGS', "Settings");
define('_EN_ECOMMERCE_LAST_UPDATE', "Last Update");
define('_EN_ECOMMERCE_NO_ORDERS', "No orders were found.");
define('_EN_ECOMMERCE_ORDER_CREATED', "The order has been created.");
define('_EN_ECOMMERCE_ORDER_UPDATED', "The order has been updated.");
define('_EN_ECOMMERCE_ORDER_DELETED', "The order has been deleted.");
define('_EN_ECOMMERCE_ORDER_MASSIVE_DELETED', "The group of orders have been deleted");
define('_EN_ECOMMERCE_SHIPPING_CREATED', "The shipping has been created.");
define('_EN_ECOMMERCE_SHIPPING_UPDATED', "The shipping has been updated.");
define('_EN_ECOMMERCE_SHIPPING_DELETED', "The shipping has been deleted.");
define('_EN_ECOMMERCE_SHIPPING_MASSIVE_DELETED', "The group of shipping instructions have been deleted");
define('_EN_ECOMMERCE_SHIPPING_AUTOUPDATED', "The shipping has been auto saved");
define('_EN_ECOMMERCE_ADDTOCART', "Add to Cart");
define('_EN_ECOMMERCE_NO_CARTITEMS', "No items are in your cart.");
define('_EN_ECOMMERCE_CART_CREATED', "The cart has been created.");
define('_EN_ECOMMERCE_CART_UPDATED', "The cart has been updated.");
define('_EN_ECOMMERCE_CART_DELETED', "The cart has been deleted.");
define('_EN_ECOMMERCE_CART_MASSIVE_DELETED', "The group of carts have been deleted");
define('_EN_ECOMMERCE_CART_AUTOUPDATED', "The cart has been auto saved");
define('_EN_ECOMMERCE_CARTITEM_CREATED', "The item has been added to your cart.");
define('_EN_ECOMMERCE_CARTITEM_UPDATED', "The item has been updated.");
define('_EN_ECOMMERCE_CARTITEM_DELETED', "The item has been removed from your cart.");
define('_EN_ECOMMERCE_CARTITEM_MASSIVE_DELETED', "The group of items have been deleted");
define('_EN_ECOMMERCE_ADD_ORDER', "Add Order");
define('_EN_ECOMMERCE_UPDATE_ORDER', "Update Order");
define('_EN_ECOMMERCE_ORDER', "Order");
define('_EN_ECOMMERCE_CONFIRM_DELETE_ORDER', "Are you sure you want to delete this order?");
define('_EN_ECOMMERCE_CONFIRM_MASIVE_DELETE_ORDER', "Are you sure you want to delete selected orders?");
define('_EN_ECOMMERCE_SHIPPING', "Shipping");
define('_EN_ECOMMERCE_ADD_SHIPPING', "Add Shipping");
define('_EN_ECOMMERCE_UPDATE_SHIPPING', "Update Shipping");
define('_EN_ECOMMERCE_CONFIRM_DELETE_SHIPPING', "Are you sure you want to delete this shipping?");
define('_EN_ECOMMERCE_CONFIRM_MASIVE_DELETE_SHIPPING', "Are you sure you want to delete selected shipping methods?");
define('_EN_ECOMMERCE_VENDOR', "Merchant");
define('_EN_ECOMMERCE_PRODUCT', "Product");
define('_EN_ECOMMERCE_PRICE', "Price");
define('_EN_ECOMMERCE_QTY', "Quantity");
define('_EN_ECOMMERCE_UNIT', "Unit");
define('_EN_ECOMMERCE_WEIGHT', "Weight");
define('_EN_ECOMMERCE_ATTRIBUTE', "Attributes");
define('_EN_ECOMMERCE_PUBLISHED', "Active");
define('_EN_ECOMMERCE_NOTPUBLISHED', "Not Active");
define('_EN_ECOMMERCE_TOTAL', "Total");
define('_EN_ECOMMERCE_BACKORDER', "Backorder");
define('_EN_ECOMMERCE_DESC', "Description");
define('_EN_ECOMMERCE_ACTIVE', "Status");
define('_EN_ECOMMERCE_STATUSUPDATE_NOTE', "Send a note about this status change?");
define('_EN_ECOMMERCE_RECURRING', "Recurring");
define('_EN_ECOMMERCE_ORDERNO', "Order Number");
define('_EN_ECOMMERCE_CUSTOMER_EMAIL', "Customer E-mail");
define('_EN_ECOMMERCE_CUSTOMER_NAME', "Billing Name");
define('_EN_ECOMMERCE_CUSTOMER_COMPANY', "Billing Company");
define('_EN_ECOMMERCE_CUSTOMER_ADDRESS', "Billing Address");
define('_EN_ECOMMERCE_CUSTOMER_ADDRESS2', "Billing Address 2");
define('_EN_ECOMMERCE_CUSTOMER_CITY', "Billing City");
define('_EN_ECOMMERCE_CUSTOMER_REGION', "Billing Region");
define('_EN_ECOMMERCE_CUSTOMER_POSTAL', "Billing Postal");
define('_EN_ECOMMERCE_CUSTOMER_COUNTRY', "Billing Country");
define('_EN_ECOMMERCE_CUSTOMER_PHONE', "Customer Phone");
define('_EN_ECOMMERCE_CUSTOMER_FAX', "Customer Fax");
define('_EN_ECOMMERCE_CUSTOMER_SHIPNAME', "Shipping Name");
define('_EN_ECOMMERCE_CUSTOMER_SHIPADDRESS', "Shipping Address");
define('_EN_ECOMMERCE_CUSTOMER_SHIPADDRESS2', "Shipping Address 2");
define('_EN_ECOMMERCE_CUSTOMER_SHIPCITY', "Shipping City");
define('_EN_ECOMMERCE_CUSTOMER_SHIPREGION', "Shipping Region");
define('_EN_ECOMMERCE_CUSTOMER_SHIPPOSTAL', "Shipping Postal");
define('_EN_ECOMMERCE_CUSTOMER_SHIPCOUNTRY', "Shipping Country");
define('_EN_ECOMMERCE_SHIP_MINFACTOR', "Min Factor");
define('_EN_ECOMMERCE_SHIP_MAXFACTOR', "Max Factor");
define('_EN_ECOMMERCE_CARRIERCALCULATED', "Carrier Calculated");
define('_EN_ECOMMERCE_SHIPBYWEIGHT', "Ship By Weight");
define('_EN_ECOMMERCE_SHIPBYPRICE', "Ship By Price");
define('_EN_ECOMMERCE_SHIPBYPRODUCTS', "Ship By Number of Products");
define('_EN_ECOMMERCE_TYPE', "Type");
define('_EN_ECOMMERCE_DEFAULT', "Default");
define('_EN_ECOMMERCE_SETTINGS_SSL_LINK', "E-commerce requires an SSL-enabled server. Click Here to enter the SSL-enabled URL to use for your site.");
define('_EN_ECOMMERCE_SETTINGS_UPDATED', "Settings have been updated.");
define('_EN_ECOMMERCE_SETTINGS_PAYMENT_GATEWAY', "Payment Gateway");
define('_EN_ECOMMERCE_SETTINGS_SHIPPING_OPTIONS', "Shipping Options");
define('_EN_ECOMMERCE_SETTINGS_SHIPPING_LINK', "Click Here to Setup Shipping Options");
define('_EN_ECOMMERCE_SETTINGS_MANUALCREDITCARD', "Manual (Credit Card)");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL', "PayPal");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL_ID', "API Username");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL_KEY', "API Password");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL_SIGNATURE', "API Signature");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL_LINK', "Step 1: Click Here to Setup a Merchant Account to use PayPal, if you don't already have one");
define('_EN_ECOMMERCE_SETTINGS_PAYPAL_STEP2', "Step 2: Enter your API Username, API Password and API Signature into the text boxes below. Click Here to find them, if you don't know them");
define('_EN_ECOMMERCE_SETTINGS_GOOGLECHECKOUT', "Google Checkout");
define('_EN_ECOMMERCE_SETTINGS_GOOGLECHECKOUT_LINK', "Step 1: Click Here to Setup a Merchant Account to use Google Checkout, if you don't already have one");
define('_EN_ECOMMERCE_SETTINGS_GOOGLECHECKOUT_INTEGRATION', "Step 2: Copy the URL below. Click Here and sign-in to your Merchant Account, if you're not already. On the Integration page, paste this URL into the 'API Callback URL' text box");
define('_EN_ECOMMERCE_SETTINGS_GOOGLECHECKOUT_STEP3', "Step 3: Enter your Merchant ID and Merchant Key into the text boxes below. Click Here to find them, if you don't know them");
define('_EN_ECOMMERCE_SETTINGS_GOOGLECHECKOUT_INTEGRATION_URL', "API Callback URL");
define('_EN_ECOMMERCE_SETTINGS_AUTHORIZENET', "Authorize.NET");
define('_EN_ECOMMERCE_SETTINGS_AUTHORIZENET_LINK', "Step 1: Click Here to Setup a Merchant Account to use Authorize.NET, if you don't already have one");
define('_EN_ECOMMERCE_SETTINGS_AUTHORIZENET_INTEGRATION', "Step 2: Highlight and Copy the URL below. Click Here and sign-in to your Merchant Account, if you're not already. Click on the 'Account' tab, click 'Settings', then click the 'Response/Receipt URLs' link. Click 'Edit' next to 'Default Relay Response URL'. Paste this URL into the 'URL' text box. Click 'Submit'.");
define('_EN_ECOMMERCE_SETTINGS_AUTHORIZENET_STEP3', "Step 3: Enter your API Login ID and Transaction Key into the text boxes below. If you don't know them, Click Here and sign-in. Click on the 'Account' tab, click 'Settings', then click the 'API Login ID / Transaction Key' link. Follow the instructions on the page.");
define('_EN_ECOMMERCE_SETTINGS_AUTHORIZENET_INTEGRATION_URL', "Default Receipt Link URL");
define('_EN_ECOMMERCE_SETTINGS_GATEWAY_ID', "Merchant ID");
define('_EN_ECOMMERCE_SETTINGS_GATEWAY_KEY', "Merchant Key");
define('_EN_ECOMMERCE_SETTINGS_GATEWAY_SIGNATURE', "Merchant Signature");
define('_EN_ECOMMERCE_SETTINGS_GATEWAY_LOGO', "Your E-commerce Logo");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_EXPIRING_FREQ', "How Often Customers are Notified Before Subscriptions Expire");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_1DAY', "&nbsp;&nbsp;1 Day Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_2DAY', "&nbsp;&nbsp;2 Days Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_3DAY', "&nbsp;&nbsp;3 Days Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_5DAY', "&nbsp;&nbsp;5 Days Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_10DAY', "&nbsp;&nbsp;10 Days Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_15DAY', "&nbsp;&nbsp;15 Days Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_1MONTH', "&nbsp;&nbsp;1 Month Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_2MONTH', "&nbsp;&nbsp;2 Months Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_3MONTH', "&nbsp;&nbsp;3 Months Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_6MONTH', "&nbsp;&nbsp;6 Months Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_9MONTH', "&nbsp;&nbsp;9 Months Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_NOTIFY_1YEAR', "&nbsp;&nbsp;1 Year Before Expiring");
define('_EN_ECOMMERCE_SETTINGS_SHIPFROM_ADDRESS', "Ship Packages From This Address");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_FEES', "Transaction Fees");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_PERCENT', "Charge this Percentage Per Transaction");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_AMOUNT', "Charge This Amount Per Transaction");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_MODE', "Transaction Fee Mode");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_MODE_SUBTRACT', "Subtract From Payments Paid To Merchants");
define('_EN_ECOMMERCE_SETTINGS_TRANSACTION_MODE_ADD', "Add To Total Amount at Checkout");
define('_EN_ECOMMERCE_SETTINGS_TERMS', "Checkout Terms");
define('_EN_ECOMMERCE_CART_TAX_SHIPPING_NEXT', "Tax and Shipping Calculated Next");
define('_EN_ECOMMERCE_USER_TAXES_DELETED', "The user's tax rules have been deleted.");
define('_EN_ECOMMERCE_USER_SHIPPINGS_DELETED', "The user's shipping rules have been deleted.");
define('_EN_ECOMMERCE_USER_ORDERS_UPDATED', "The user's orders have been updated.");
