<?php
// General Translation file (i18n) for Ads gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Ads"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_ADS_NAME', "Ads");
define('_EN_ADS_DESCRIPTION', "A gadget to create and manage advertisements.");

// Actions

// Layout elements
define('_EN_ADS_LAYOUT_TWOBUTTONS_TITLE', "Two Buttons");
define('_EN_ADS_LAYOUT_TWOBUTTONS_DESCRIPTION', "Displays two 125x125 advertisements.");
define('_EN_ADS_LAYOUT_FOURBUTTONS_TITLE', "Four Buttons");
define('_EN_ADS_LAYOUT_FOURBUTTONS_DESCRIPTION', "Displays four 125x125 advertisements.");
define('_EN_ADS_LAYOUT_TWOBLOCKS_TITLE', "Two Blocks");
define('_EN_ADS_LAYOUT_TWOBLOCKS_DESCRIPTION', "Displays two 225x200 advertisements.");
define('_EN_ADS_LAYOUT_FOURBLOCKS_TITLE', "Four Blocks");
define('_EN_ADS_LAYOUT_FOURBLOCKS_DESCRIPTION', "Displays four 225x200 advertisements.");
define('_EN_ADS_LAYOUT_LEADERBOARD_TITLE', "Leader Board");
define('_EN_ADS_LAYOUT_LEADERBOARD_DESCRIPTION', "Displays a 728x90 banner advertisement.");
define('_EN_ADS_LAYOUT_BANNER_TITLE', "Banner");
define('_EN_ADS_LAYOUT_BANNER_DESCRIPTION', "Displays a 468x60 banner advertisement.");
define('_EN_ADS_LAYOUT_DEFAULT_TITLE', "Advertise Here");
define('_EN_ADS_LAYOUT_DEFAULT_TEXT', "Advertise Here");
define('_EN_ADS_LAYOUT_DEFAULT_DESCRIPTION', "Display an 'Advertise Here' ad for your site.");
define('_EN_ADS_LAYOUT_AD_DESCRIPTION', "Display a specific advertisement.");

// ACLs
define('_EN_ADS_ACL_DEFAULT', "Adminstrate Ads");
define('_EN_ADS_ACL_OWNADS', "Add/Edit/Delete their own Ads");
define('_EN_ADS_ACL_MANAGEADS', "Manage Ads");
define('_EN_ADS_ACL_MANAGEPUBLICADS', "Manage Public Ads");

// Errors
define('_EN_ADS_ERROR_ADPARENT_NOT_ADDED', "There was a problem adding the category.");
define('_EN_ADS_ERROR_ADPARENT_NOT_UPDATED', "There was a problem updating the category.");
define('_EN_ADS_ERROR_ADPARENT_NOT_DELETED', "There was a problem deleting the category.");
define('_EN_ADS_ERROR_ADPARENT_NOT_FOUND', "The category you requested could not be found.");
define('_EN_ADS_ERROR_ADPARENT_NOT_LINKED', "There was a problem linking the category.");
define('_EN_ADS_ERROR_ADPARENT_NOT_UNLINKED', "There was a problem unlinking the category.");
define('_EN_ADS_ERROR_AD_NOT_ADDED', "There was a problem adding the ad.");
define('_EN_ADS_ERROR_AD_NOT_UPDATED', "There was a problem updating the ad.");
define('_EN_ADS_ERROR_AD_NOT_DELETED', "There was a problem deleting the ad.");
define('_EN_ADS_ERROR_AD_NOT_FOUND', "The ad you requested could not be found.");
define('_EN_ADS_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_ADS_ERROR_BRAND_NOT_ADDED', "There was a problem adding the brand.");
define('_EN_ADS_ERROR_BRAND_NOT_UPDATED', "There was a problem updating the brand.");
define('_EN_ADS_ERROR_BRAND_NOT_DELETED', "There was a problem deleting the brand.");
define('_EN_ADS_ERROR_BRAND_NOT_FOUND', "The brand you requested could not be found.");
define('_EN_ADS_ERROR_ADS_NOT_RETRIEVED', "The ads could not be loaded.");
define('_EN_ADS_ERROR_INDEX_NOT_LOADED', "The advertisement index could not be loaded.");
define('_EN_ADS_ERROR_AD_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of ads.");
define('_EN_ADS_ERROR_ASPPAGE_NOT_RETRIEVED', "The Advertisement could not be loaded: {0}.");
define('_EN_ADS_ERROR_ADCLICK_NOT_ADDED', "The ad click was not tracked.");
define('_EN_ADS_ERROR_INVALID_URL', "The URL you've entered is malformed. It must begin with 'http://'");
define('_EN_ADS_ERROR_INVALID_IMAGE', "Only .JPG, .GIF, .PNG and .SWF files are allowed in Ads.");
define('_EN_ADS_ERROR_USER_ADBRANDS_NOT_DELETED', "There was a problem deleting the user's ad brands.");
define('_EN_ADS_ERROR_USER_ADBRAND_NOT_DELETED', "There was a problem deleting the user's ad brand.");
define('_EN_ADS_ERROR_USER_ADS_NOT_DELETED', "There was a problem deleting the user's ads.");
define('_EN_ADS_ERROR_USER_AD_NOT_DELETED', "There was a problem deleting the user's ad.");
define('_EN_ADS_ERROR_USER_ADPARENTS_NOT_DELETED', "There was a problem deleting the user's ad categories.");
define('_EN_ADS_ERROR_USER_ADPARENT_NOT_DELETED', "There was a problem deleting the user's ad category.");
define('_EN_ADS_ERROR_USER_ADS_NOT_UPDATED', "There was a problem updating the user's ads.");
define('_EN_ADS_ERROR_USER_ADBRANDS_NOT_UPDATED', "There was a problem updating the user's ad brands.");
define('_EN_ADS_ERROR_USER_ADPARENTS_NOT_UPDATED', "There was a problem updating the user's ad categories.");

// Strings
define('_EN_ADS_TITLE_AD_INDEX', "Advertisement Index");
define('_EN_ADS_TITLE_NOT_FOUND', "Advertisement Not Found");
define('_EN_ADS_CONTENT_NOT_FOUND', "The ad you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_ADS_MENU_ADMIN', "View Categories");
define('_EN_ADS_MENU_CATEGORY', "Edit Category");
define('_EN_ADS_MENU_ADS', "View Ads");
define('_EN_ADS_MENU_AD', "Edit Advertisement");
define('_EN_ADS_MENU_BRANDS', "View Brands");
define('_EN_ADS_MENU_BRAND', "Edit Brand");
define('_EN_ADS_LAST_UPDATE', "Last Update");
define('_EN_ADS_NO_ADS', "No ads were found.");
define('_EN_ADS_AD_KEYWORD', "Keywords");
define('_EN_ADS_ADCLICK_ADDED', "The ad click was successfully tracked.");
define('_EN_ADS_ADPARENT_CREATED', "The category has been created.");
define('_EN_ADS_ADPARENT_UPDATED', "The category has been updated.");
define('_EN_ADS_ADPARENT_DELETED', "The category has been deleted.");
define('_EN_ADS_ADPARENT_MASSIVE_DELETED', "The group of categories have been deleted.");
define('_EN_ADS_ADPARENT_AUTOUPDATED', "The category has been auto saved.");
define('_EN_ADS_AD_CREATED', "The ad has been created.");
define('_EN_ADS_AD_UPDATED', "The ad has been updated.");
define('_EN_ADS_AD_DELETED', "The ad has been deleted.");
define('_EN_ADS_BRAND_CREATED', "The brand has been created.");
define('_EN_ADS_BRAND_UPDATED', "The brand has been updated.");
define('_EN_ADS_BRAND_DELETED', "The brand has been deleted.");
define('_EN_ADS_BRAND_MASSIVE_DELETED', "The group of brands have been deleted.");
define('_EN_ADS_BRAND_AUTOUPDATED', "The brand has been auto saved.");
define('_EN_ADS_AD_MASSIVE_DELETED', "The group of ads have been deleted.");
define('_EN_ADS_AD_AUTOUPDATED', "The ad has been auto saved.");
define('_EN_ADS_ADD_ADPARENT', "Add Category");
define('_EN_ADS_ADD_AD', "Add Advertisement");
define('_EN_ADS_UPDATE_AD', "Update Ad");
define('_EN_ADS_AD', "Ad");
define('_EN_ADS_CONFIRM_DELETE_AD', "Are you sure you want to delete this ad?");
define('_EN_ADS_CONFIRM_MASIVE_DELETE_AD', "Are you sure you want to delete selected ads?");
define('_EN_ADS_ADS', "Ads");
define('_EN_ADS_PARENT', "Parent");
define('_EN_ADS_CATEGORY', "Category");
define('_EN_ADS_DESCRIPTIONFIELD', "Description");
define('_EN_ADS_TITLE', "Title");
define('_EN_ADS_ADTITLE', "Ad Title");
define('_EN_ADS_ADIMAGE', "Ad Image");
define('_EN_ADS_IMAGE', "Image");
define('_EN_ADS_PUBLISHED', "Published");
define('_EN_ADS_NOTPUBLISHED', "Inactive");
define('_EN_ADS_STATUS', "Status");
define('_EN_ADS_ACTIVE', "Active");
define('_EN_ADS_TYPE', "Type");
define('_EN_ADS_TYPE_125', "Button");
define('_EN_ADS_TYPE_468', "Banner");
define('_EN_ADS_TYPE_728', "Leader Board");
define('_EN_ADS_KEYWORD', "Keyword(s)");
define('_EN_ADS_SITEWIDE', "Sitewide");
define('_EN_ADS_URL', "URL");
define('_EN_ADS_URLTYPE', "URL Type");
define('_EN_ADS_INTERNALURL', "Internal URL");
define('_EN_ADS_EXTERNALURL', "External URL");
define('_EN_ADS_URLTARGET', "URL Target");
define('_EN_ADS_USER_ADBRANDS_DELETED', "The user's ad brands have been deleted.");
define('_EN_ADS_USER_ADS_DELETED', "The user's ads have been deleted.");
define('_EN_ADS_USER_ADPARENTS_DELETED', "The user's ad categories have been deleted.");
define('_EN_ADS_USER_ADS_UPDATED', "The user's ads have been updated.");
define('_EN_ADS_QUICKADD_ADDADPARENT', "Ad Category");
define('_EN_ADS_QUICKADD_ADDAD', "Advertisement");
