<?php
// General Translation file (i18n) for WHMCS gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: WHMCS"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_WHMCS_NAME', "WHMCS");
define('_EN_WHMCS_DESCRIPTION', "A gadget to interact with WHMCS.");

// Actions

// Layout elements

// ACLs
define('_EN_WHMCS_ACL_DEFAULT', "Adminstrate WHMCS");

// Errors
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_ADDED', "There was a problem adding the client.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_UPDATED', "There was a problem updating the client.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_DELETED', "There was a problem deleting the client.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_FOUND', "The client you requested could not be found.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_LINKED', "There was a problem linking the client.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_UNLINKED', "There was a problem unlinking the client.");
define('_EN_WHMCS_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
define('_EN_WHMCS_ERROR_WHMCS_USERS_NOT_RETRIEVED', "The clients could not be loaded.");
define('_EN_WHMCS_ERROR_WHMCS_USER_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of clients.");
define('_EN_WHMCS_ERROR_WHMCS_API_CREDENTIALS_NOT_VALID', "The WHMCS API credentials for this site could not be validated.");
define('_EN_WHMCS_ERROR_ASPPAGE_NOT_RETRIEVED', "The page you requested could not be loaded: {0}");

// Responses
define('_EN_WHMCS_WHMCS_USER_CREATED', "The client has been created.");
define('_EN_WHMCS_WHMCS_USER_UPDATED', "The client has been updated.");
define('_EN_WHMCS_WHMCS_USER_DELETED', "The client has been deleted.");
define('_EN_WHMCS_SETTINGS_UPDATED', "WHMCS Settings have been updated.");
define('_EN_WHMCS_WHMCS_USER_MASSIVE_DELETED', "The group of clients have been deleted.");
define('_EN_WHMCS_WHMCS_USER_AUTOUPDATED', "The client has been auto saved.");

// Strings
define('_EN_WHMCS_MENU_ADMIN', "View Clients");
define('_EN_WHMCS_MENU_INVOICES', "View Invoices");
define('_EN_WHMCS_MENU_CREDITS', "View Credits");
define('_EN_WHMCS_MENU_SETTINGS', "Settings");
define('_EN_WHMCS_LAST_UPDATE', "Last Update");
define('_EN_WHMCS_ADD_WHMCS_USER', "Add client");
define('_EN_WHMCS_EDIT_WHMCS_USER', "Edit client");
define('_EN_WHMCS_UPDATE_WHMCS_USER', "Update client");
define('_EN_WHMCS_CONFIRM_DELETE_WHMCS_USER', "Are you sure you want to delete this client?");
define('_EN_WHMCS_CONFIRM_MASIVE_DELETE_WHMCS_USER', "Are you sure you want to delete selected clients?");
define('_EN_WHMCS_WHMCS_ID', "WHMCS ID");
define('_EN_WHMCS_WHMCS_USER', "Client");
define('_EN_WHMCS_WHMCS_USERS', "Clients");
define('_EN_WHMCS_WHMCS_API_URL', "API URL Endpoint");
define('_EN_WHMCS_WHMCS_API_USER', "API User");
define('_EN_WHMCS_WHMCS_API_AUTH', "API Auth Key");
define('_EN_WHMCS_SETTINGS_API', "WHMCS API Settings");
