<?php
// General Translation file (i18n) for Maps gadget
// Jaws 2005 <c>
// Generated by: Generatei18N.pl Perl Script <Jaws Developers>
//

/**
 * Meta Data
 *
 * "Project-Id-Version: Maps"
 * "Last-Translator: Alan Valkoun"
 * "Language-Team: EN"
 * "MIME-Version: 1.0"
 * "Content-Type: text/plain; charset=UTF-8"
 * "Content-Transfer-Encoding: 8bit"
 */

define('_EN_MAPS_NAME', "Maps");
define('_EN_MAPS_DESCRIPTION', "A gadget to create and manage Google Maps.");

// Actions
define('_EN_MAPS_ACTION_INDEX', "Display an index of maps.");
define('_EN_MAPS_ACTION_MAP', "Display a single map.");

// Layout elements
define('_EN_MAPS_LAYOUT_DISPLAY', "Google Map");
define('_EN_MAPS_LAYOUT_DISPLAY_DESCRIPTION', "Displays a Google Map.");

// ACLs
define('_EN_MAPS_ACL_DEFAULT', "Adminstrate Maps");
define('_EN_MAPS_ACL_OWNMAP', "Add/Edit/Delete their own Maps");
define('_EN_MAPS_ACL_MANAGEMAPS', "Manage Maps");
define('_EN_MAPS_ACL_MANAGEPUBLICMAPS', "Manage Public Maps");

// Errors
define('_EN_MAPS_ERROR_MAP_NOT_ADDED', "There was a problem adding the map.");
define('_EN_MAPS_ERROR_MAP_NOT_UPDATED', "There was a problem updating the map.");
define('_EN_MAPS_ERROR_MAP_NOT_DELETED', "There was a problem deleting the map.");
define('_EN_MAPS_ERROR_MAP_NOT_FOUND', "The map you requested could not be found.");
define('_EN_MAPS_ERROR_POST_NOT_ADDED', "There was a problem adding the location.");
define('_EN_MAPS_ERROR_POST_NOT_UPDATED', "There was a problem updating the location.");
define('_EN_MAPS_ERROR_POST_NOT_DELETED', "There was a problem deleting the location.");
define('_EN_MAPS_ERROR_POST_NOT_FOUND', "The location you requested could not be found.");
define('_EN_MAPS_ERROR_UNKNOWN_COLUMN', "An unknown sort column was provided.");
///FIXME they should not have the same translation.
define('_EN_MAPS_ERROR_MAPS_NOT_RETRIEVED', "The map index could not be loaded.");
define('_EN_MAPS_ERROR_REGIONS_NOT_RETRIEVED', "The region index could not be loaded.");
define('_EN_MAPS_ERROR_INDEX_NOT_LOADED', "The map index could not be loaded.");
define('_EN_MAPS_ERROR_MAP_NOT_MASSIVE_DELETED', "There was a problem while deleting the group of maps");
define('_EN_MAPS_ERROR_ASPPAGE_NOT_RETRIEVED', "The page could not be loaded: {0}.");
define('_EN_MAPS_ERROR_GADGETCONTENT_NOT_RETRIEVED', "The requested Gadget content could not be loaded: {0}.");
define('_EN_MAPS_ERROR_KEY_NOT_SAVED', "There was a problem saving the key.");

// Strings
define('_EN_MAPS_TITLE_PAGE_INDEX', "Map Index");
define('_EN_MAPS_TITLE_NOT_FOUND', "Map Not Found");
define('_EN_MAPS_CONTENT_NOT_FOUND', "The map you requested could not be found, please contact the site administrator if you believe it should exist.");
define('_EN_MAPS_MENU_ADMIN', "View Maps");
define('_EN_MAPS_MENU_MAP', "Edit Map");
define('_EN_MAPS_MENU_POST', "Edit Location");
define('_EN_MAPS_MENU_PROPERTIES', "Settings");
define('_EN_MAPS_LAST_UPDATE', "Last Update");
define('_EN_MAPS_NO_MAP', "No maps were found.");
define('_EN_MAPS_POST_CREATED', "The location has been created.");
define('_EN_MAPS_POST_UPDATED', "The location has been updated.");
define('_EN_MAPS_POST_DELETED', "The location has been deleted.");
define('_EN_MAPS_MAP_CREATED', "The map has been created.");
define('_EN_MAPS_MAP_UPDATED', "The map has been updated.");
define('_EN_MAPS_MAP_DELETED', "The map has been deleted.");
define('_EN_MAPS_MAP_MASSIVE_DELETED', "The group of maps have been deleted");
define('_EN_MAPS_MAP_AUTOUPDATED', "The map has been auto saved");
define('_EN_MAPS_ADD_MAP', "Add Map");
define('_EN_MAPS_UPDATE_MAP', "Update Map");
define('_EN_MAPS_PAGE', "Map");
define('_EN_MAPS_POSTS', "Location");
define('_EN_MAPS_POST_CONFIRM_DELETE', "Are you sure you want to delete this location?");
define('_EN_MAPS_CONFIRM_DELETE_MAP', "Are you sure you want to delete this map?");
define('_EN_MAPS_CONFIRM_MASIVE_DELETE_MAP', "Are you sure you want to delete selected maps?");
define('_EN_MAPS_DRAFT', "Not Active");
define('_EN_MAPS_PUBLISHED', "Active");
define('_EN_MAPS_ACTIVE', "Status");
define('_EN_MAPS_TITLE', "Title");
define('_EN_MAPS_GOOGLE_KEY', "Google Key");
define('_EN_MAPS_GOOGLE_EXTRA', "You must sign up for a maps key from Google for the domain: {0}. <a target=\"_blank\" href=\"http://code.google.com/apis/maps/signup.html\">Click here to sign-up for a Maps key</a>");
define('_EN_MAPS_KEY_SAVED', "The key has been saved.");

